CW-86 Create GitHub Prod workflow.
nikitamelnik1504/circled-words pull request #6
Opened 2023-01-06 18:05 UTC by 108ddy

2023-01-06 22:01 UTC, nikitamelnik1504 requested changes

2023-01-06 22:01 UTC, nikitamelnik1504 commented on .github/workflows/prod.yml
> +  remote-host-load-image:
Please remove second job for now.

2023-01-06 22:01 UTC, nikitamelnik1504 commented on src/views/page/CreateWord/index.vue
> +                      :disabled="(+asset.value === 0.1) | playRunning"
?

2023-01-06 22:05 UTC, 108ddy commented on src/views/page/CreateWord/index.vue
> +                      :disabled="(+asset.value === 0.1) | playRunning"
eslint make this

2023-01-06 22:06 UTC, nikitamelnik1504 commented on src/views/page/CreateWord/index.vue
> +                      :disabled="(+asset.value === 0.1) | playRunning"
Does your site env works now?

2023-01-19 19:41 UTC, nikitamelnik1504 approved these changes

2023-01-19 19:43 UTC, merged